# Synchronous policy evaluation

In [3]:
m,n=5,5
S=[(r,c) for r in range (m) for c in range (n)]
A=['north', 'south', 'east', 'west']
acount=len(A)
terminal=[(4,4)]
gamma=1

In [4]:
def transition(s,a, s_next):
    r,c=s
    if a=='north':
      r=r if r==0 else r-1
    if a=='south':
      r=r if r==4 else r+1
    if a=='east':
      c=c if c==4 else c+1
    if a=='west':
      c=c if c==0 else c-1
    prob=1 if (r, c)==s_next else 0
    reward = -1
    return prob, reward



In [7]:
pi={s:{a:0.25 for a in A} for s in S}
import numpy as np

In [11]:
import numpy as np

def to_numpy(v, m, n):
    vnum = np.zeros((m, n))
    for s in v:
        vnum[s] = v[s]
    return vnum

theta = 1e-3  # Smaller convergence threshold for faster convergence
gamma = 1  # Assuming a discount factor of 1
delta = theta + 1
v = {s: 0 for s in S}
iter = 0

# Assuming a random policy where pi[s][a] = 1/len(A) for all states and actions
pi = {s: {a: 1/len(A) for a in A} for s in S}

while delta >= theta:
    iter += 1
    v_next = {s: 0 for s in S}
    delta = 0

    for s in S:
        if s in terminal:
            continue  # Skip terminal states

        # Evaluate the value for each action
        for a in A:
            total_value = 0  # Initialize the expected value for this action
            for s_next in S:
                prob, reward = transition(s, a, s_next)
                total_value += prob * (reward + gamma * v[s_next])
            v_next[s] += pi[s][a] * total_value  # Update value function based on policy

        # Update delta to track the maximum change in value
        delta = max(delta, abs(v_next[s] - v[s]))

    v = v_next.copy()  # Update the value function for the next iteration

# Round the value function for easier interpretation
v = {s: np.round(v[s], 2) for s in S}

# Print the number of iterations and the final value function
print(f"Number of iterations: {iter}")
print("Value function:")
print(v)

# Convert the value function to a NumPy array and print
v_array = to_numpy(v, m, n)
print(v_array)


Number of iterations: 647
Value function:
{(0, 0): -106.73, (0, 1): -104.73, (0, 2): -101.29, (0, 3): -97.54, (0, 4): -95.0, (1, 0): -104.73, (1, 1): -102.17, (1, 2): -97.62, (1, 3): -92.33, (1, 4): -88.46, (2, 0): -101.29, (2, 1): -97.62, (2, 2): -90.67, (2, 3): -81.72, (2, 4): -74.05, (3, 0): -97.54, (3, 1): -92.33, (3, 2): -81.72, (3, 3): -65.84, (3, 4): -47.96, (4, 0): -95.0, (4, 1): -88.46, (4, 2): -74.05, (4, 3): -47.96, (4, 4): 0}
[[-106.73 -104.73 -101.29  -97.54  -95.  ]
 [-104.73 -102.17  -97.62  -92.33  -88.46]
 [-101.29  -97.62  -90.67  -81.72  -74.05]
 [ -97.54  -92.33  -81.72  -65.84  -47.96]
 [ -95.    -88.46  -74.05  -47.96    0.  ]]


In [12]:
import numpy as np

def to_numpy(v, m, n):
    vnum = np.zeros((m, n))
    for s in v:
        vnum[s] = v[s]
    return vnum

theta = 1e-3  # Convergence threshold
gamma = 1  # Discount factor
delta = theta + 1
v = {s: 0 for s in S}  # Initialize value function to 0 for all states
iter = 0

# Assuming a random policy where pi[s][a] = 1/len(A) for all states and actions
pi = {s: {a: 1/len(A) for a in A} for s in S}

while delta >= theta:
    iter += 1
    delta = 0

    for s in S:
        if s in terminal:
            continue  # Skip terminal states

        # Save the current value of the state for delta calculation later
        v_old = v[s]

        # Initialize new value for state s
        new_value = 0

        # Iterate over all actions
        for a in A:
            total_value = 0  # Expected value for the action a

            # Iterate over all possible next states
            for s_next in S:
                prob, reward = transition(s, a, s_next)
                total_value += prob * (reward + gamma * v[s_next])

            # Update the value of the state s based on the current policy
            new_value += pi[s][a] * total_value

        # In-place update of the value function
        v[s] = new_value

        # Update delta to track the maximum change in value
        delta = max(delta, abs(v[s] - v_old))

# Round the value function for easier interpretation
v = {s: np.round(v[s], 2) for s in S}

# Print the number of iterations and the final value function
print(f"Number of iterations: {iter}")
print("Value function:")
print(v)

# Convert the value function to a NumPy array and print
v_array = to_numpy(v, m, n)
print(v_array)


Number of iterations: 419
Value function:
{(0, 0): -106.76, (0, 1): -104.77, (0, 2): -101.33, (0, 3): -97.57, (0, 4): -95.03, (1, 0): -104.77, (1, 1): -102.21, (1, 2): -97.65, (1, 3): -92.37, (1, 4): -88.49, (2, 0): -101.33, (2, 1): -97.65, (2, 2): -90.7, (2, 3): -81.75, (2, 4): -74.07, (3, 0): -97.57, (3, 1): -92.37, (3, 2): -81.75, (3, 3): -65.86, (3, 4): -47.98, (4, 0): -95.03, (4, 1): -88.49, (4, 2): -74.07, (4, 3): -47.98, (4, 4): 0}
[[-106.76 -104.77 -101.33  -97.57  -95.03]
 [-104.77 -102.21  -97.65  -92.37  -88.49]
 [-101.33  -97.65  -90.7   -81.75  -74.07]
 [ -97.57  -92.37  -81.75  -65.86  -47.98]
 [ -95.03  -88.49  -74.07  -47.98    0.  ]]
